# .github/FUNDING.yml

# GitHub Sponsors (use brackets [] even for a single username)
github: [https://github.com/mahdidarbaj-cmd]  

# Patreon (optional)
patreon: YourPatreonUsername  

# Ko-fi (optional)
ko_fi: YourKoFiUsername  

# Buy Me a Coffee (optional)
buy_me_a_coffee: YourCoffeeUsername  

# Custom links (optional, up to 4 URLs)
custom: ['https://example.com/donate1', 'https://example.com/donate2']
